// The order of these models is important for database row creation!
module.exports = [
  'ACL',
  'AccessToken',
  'Role',
  'RoleMapping',
  'History',
  'Purchaseuser',
  'Title',
  'Titlegroup',
  'Account',
  'Supplier',
  'Delivery',
  'Costcenter',
  'Purchaseorder',
  'Purchaseorderrow',
  'PurchaseuserCostcenter',
  'Externalorder',
  'ArrivedDelivery',
  'ArrivedDeliveryRow',
];
